inherits:
  - strictness_veryhigh
  - full_pep8
  - doc_warnings

ignore-paths:
  - .git
  - setup.py
  - build
  - serverauditor_sshconfig/core/ssh_config.py  # it's too complex

pep257:
  disable:
    - D203  # 1 blank line required before

pylint:
  options:
    max-parents: 12

