inherits:
  - strictness_veryhigh
  - full_pep8
  - doc_warnings

ignore-paths:
  - .git
  - setup.py
  - build
  - serverauditor_sshconfig/core/ssh_config.py  # it's too complex

pep257:
  disable:
    - D100  # TODO remove it when done with code style fixing.
    - D101  # TODO remove it when done with code style fixing.
    - D102  # TODO remove it when done with code style fixing.
    - D103  # TODO remove it when done with code style fixing.
    - D104  # TODO remove it when done with code style fixing.
    - D105  # TODO remove it when done with code style fixing.
    - D203  # 1 blank line required before

pylint:
  options:
    max-parents: 12

