inherits:
  - strictness_veryhigh
  - full_pep8
  - doc_warnings

ignore-paths:
  - .git
  - setup.py
  - build
  - tests
  - serverauditor_sshconfig/core/ssh_config.py  # it's too complex
  - serverauditor_sshconfig/core/cryptor.py  # it's too complex
  - serverauditor_sshconfig/core/utils.py  # it's too complex

ignore-patterns:
  - (^|/)(?!serverauditor_sshconfig)?(/|$)

pep257:
  disable:
    - D203  # 1 blank line required before
    - D213

pylint:
  options:
    max-parents: 12
  enable:
    - fixme
  disable:
    - super-on-old-class

pyroma:
  run: true

mccabe:
  options:
    max-complexity: 6
